# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml
#

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'


steps:
- task: Npm@1
  inputs:
    command: 'install'

- task: NodeTool@0
  inputs:
    versionSpec: '8.x'
  displayName: 'Install Node.js'

- script: |
    nvm install 8
    Npm install yarn
    Npm install gulp
    Npm install gulp production
    Npm install
    Npm run setup
    Npm run production
    Npm run test
    Npm run hash
  displayName: 'npm install and build'
  workingDirectory: api

- task: CopyFiles@2
  inputs:
   SourceFolder: $(build.sourcesdirectory)
   Contents: 'mybuild.msi'
   TargetFolder: $(build.artifactstagingdirectory)

- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(build.SourcesDirectory)'
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/ARCHIVE.zip'
    replaceExistingArchive: true

- task: PublishBuildArtifacts@1
  inputs:
    artifactName: dist
    pathtoPublish: $(build.artifactstagingdirectory)
 


